
    <h1>Gestion des Enseignants</h1>
    <section class="table-container">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Email</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($listeEnseignants as $enseignants): ?>
                    <tr>
                        <td><?php echo $enseignants['id']?></td>
                        <td><?php echo $enseignants['nom']?></td>
                        <td><?php echo $enseignants['prenom']?></td>
                        <td><?php echo $enseignants['email']?></td>
                        <td>
                            <button class="btn-edit"><a href="update-enseignant?id=<?php echo htmlspecialchars($enseignants['id'], ENT_QUOTES, 'UTF-8'); ?>">Éditer</a></button>
                            <button class="btn-delete"><a href="delete-enseignant?id=<?php echo htmlspecialchars($enseignants['id'], ENT_QUOTES, 'UTF-8'); ?>">Supprimer</a></button>
                        </td>
                    </tr>
                <?php endforeach; ?>
                <!-- Ajouter d'autres lignes ici pour plus d'utilisateurs -->
            </tbody>
        </table>
    </section>
    <h3>Voulez-vous ajouter un nouvel enseignant ?</h3>
        <button><a href="index.php?url=register-enseignant">Ajouter</a></button>
