
<!DOCTYPE html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="style.css">
        <script type="text/javascript" defer src="public/js/script.js"></script>
    </head>
    
    <body>
       
        <!-- Créer méthode qui va récupérer toutes les promos de la bdd 
        pour rendre le select dynamique -->
        <form action="<?=$_SERVER['REQUEST_URI']?>" method="POST">
        <!--faire requete -->
        <p>Promotion: <select name="promo" id="promos" onchange="envoyerRequetePromotion()">
                    <option value="0">- </option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                </select>
        

               <!--<label for="date">Date de présence :</label>
                <input type="date" name="date_presence" value="2024-01-10">!-->
            </p>    
        <table>
                <thead>
                    <tr>
                        <th>nom</th>
                        <th>prenom</th>
                        <th>promotion</th>
                        <th>status</th>
                    </tr>
                </thead>
                <tbody id='class'>
                </tbody>
        </table>    
            <input type="submit" >
        </form>
        
    </body>
</html>