<h1>Tableau de Bord</h1>

    
<section class="dashboard-item">
    <a href=""><h2>Nombre d'Étudiants</h2>
    <div class="value">1200</div></a>
</section>

<section class="dashboard-item">
    <h2>Nombre d'Enseignants</h2>
    <div class="value">80</div>
</section>

<section class="dashboard-item">
    <h2>Notes Enregistrées</h2>
    <div class="value">3100</div>
</section>

<section class="dashboard-item">
    <h2>Présences Enregistrées</h2>
    <div class="value">2500</div>
</section>
