<!DOCTYPE html>
<html lang="en">
<body>
    


        <section class="st-1">
            <svg xmlns="http://www.w3.org/2000/svg" style="display:none;">
                <symbol id="svg-1073" viewBox="0 0 160 150">
                    <path d="M43.2,126.9c14.2,1.3,27.6,7,39.1,15.6c8.3,6.1,19.4,10.3,32.7,5.3c11.7-4.4,18.6-17.4,21-30.2c2.6-13.3,8.1-25.9,15.7-37.1
                    c8.3-12.1,10.8-27.9,5.3-42.7C150.5,20.3,134.6,9,117,7.6C107.9,6.9,98.8,5,90.1,1.9C83-0.6,75-0.7,67.4,2.1
                    c-9.9,3.7-17,11.6-20.1,21c-3.3,10.1-10.9,18-20.6,22.2c-0.1,0-0.1,0.1-0.2,0.1c-20.3,8.9-31,32-24.6,53.2
                    C6.9,115.6,25.2,125.2,43.2,126.9z"></path>
                </symbol>
            </svg>

            <div class="circle-1"></div>
            <svg class="u-svg-link" preserveAspectRatio="none" viewBox="0 0 180 190" y="0px" x="0px">
                <use href="#svg-1073"></use>
            </svg>  
            <div class="st-1-img"><img src="./public/images/f.jpg" alt=""></div>
            <div class="block">
                <h5 class="u-text u-text-default u-text-1"> Quality education <br>
                </h5>
                <h1 class="u-text u-text-2"> Education for health and well-being</h1>
                <p class="u-text u-text-3">Image from <a href="https://www.freepik.com/photos/woman">Freepik</a>
                </p>
            </div>

        </section>
        <section class="st-2">
            <div class="d-st-2">
                <div class="st-d-p">
                    <img src="./public/images/1436716-b30e0aff.png" alt="">
                    <h5 class="st-2-h5">Study Time</h5>
                    <p>Sample text. Click to select the text box. Click again or double click to start editing the text.
                    </p>
                </div>
            </div>

            <div class="d-st-1">
                <div class="st-d-p">
                    <img src="./public/images/3068380-d506fbfa.png" alt="">
                    <h5 class="st-2-h5">Study Time</h5>
                    <p>Sample text. Click to select the text box. Click again or double click to start editing the text.
                    </p>
                </div>
            </div>

            <div class="d-st-2">
                <div class="st-d-p">
                    <img src="./public/images/684831-948597b6.png" alt="">
                    <h5 class="st-2-h5">Study Time</h5>
                    <p>Sample text. Click to select the text box. Click again or double click to start editing the text.
                    </p>
                </div>
            </div>


        </section>
        <section class="st-3">
            <div>
                <h2>Essential Study Tips for Effective Learning</h2>
            </div>

            <div>

                <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco
                    laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
                    velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                    culpa qui officia
                    deserunt mollit anim id est laborum.
                </p>
                <button><a href="#"> READ MORE</a></button>
            </div>
        </section>


        <svg xmlns="http://www.w3.org/2000/svg" style="display:none;">
            <symbol id="svg-1074" viewBox="0 0 160 150">
                <path d="M43.2,126.9c14.2,1.3,27.6,7,39.1,15.6c8.3,6.1,19.4,10.3,32.7,5.3c11.7-4.4,18.6-17.4,21-30.2c2.6-13.3,8.1-25.9,15.7-37.1
        c8.3-12.1,10.8-27.9,5.3-42.7C150.5,20.3,134.6,9,117,7.6C107.9,6.9,98.8,5,90.1,1.9C83-0.6,75-0.7,67.4,2.1
        c-9.9,3.7-17,11.6-20.1,21c-3.3,10.1-10.9,18-20.6,22.2c-0.1,0-0.1,0.1-0.2,0.1c-20.3,8.9-31,32-24.6,53.2
        C6.9,115.6,25.2,125.2,43.2,126.9z"></path>
            </symbol>

        </svg>
        <section class="st-4 ">


            <div class="d-st-4">
                <div class="row">
                    <div class="block-st-4-1">
                    </div>
                    <div class="block-st-4">
                        <h3 class="u-text u-text-4"> Creativity</h3>
                        <p class="u-text u-text-5">Sample text. Click to select the text box. Click
                            again or double click to start editing the text.</p>
                        <a href="#">learn
                            more</a>
                    </div>
                    <div class="block-st-4-2">
                    </div>
                </div>
                <div class="row">

                    <div class="block-st-4">
                        <h3 class="u-text u-text-4"> Motivation</h3>
                        <p class="u-text u-text-5">Sample text. Click to select the text box. Click
                            again or double click to start editing the text.</p>
                        <a href="#">learn
                            more</a>
                    </div>

                    <div class="block-st-4-3">
                    </div>
                    <div class="block-st-4">
                        <h3 class="u-text u-text-4"> Positivity</h3>
                        <p class="u-text u-text-5">Sample text. Click to select the text box. Click
                            again or double click to start editing the text.</p>
                        <a href="#">learn
                            more</a>
                    </div>
                </div>
            </div>

            <div class="svg-st-4">
                <svg class="u-svg-link-2" preserveAspectRatio="none" viewBox="0 0 150 140" y="0px" x="0px">
                    <use href="#svg-1074"></use>
                </svg>
            </div>
            </div>
        </section>

        <section class="st-5">

            <h1>How to Learn Tech Skills</h1>
            <h5> 5 Things to Practice at Home</h5>
            <div class="st-5-trait"></div>

            <div class="text-st-5">
                <div class="u-container-layout u-container-layout-1">
                    <h3>1</h3>
                    <div class="st-5-test">
                        <h4>Teaching Methods</h4>
                        <p>Sample text. Click to select the text box. Click again or double click to start editing the
                            text.</p>
                    </div>
                </div>
                <div class="u-container-layout u-container-layout-1">
                    <h3>2</h3>
                    <div class="st-5-test">

                        <h4>Teaching Methods</h4>
                        <p>Sample text. Click to select the text box. Click again or double click to start editing the
                            text.</p>
                    </div>

                </div>
                <div class=" u-container-layout u-container-layout-1">
                    <h3>3</h3>
                    <div class="st-5-test">

                        <h4>Teaching Methods</h4>
                        <p>Sample text. Click to select the text box. Click again or double click to start editing the
                            text.</p>
                    </div>

                </div>
            </div>
        </section>

        <svg xmlns="http://www.w3.org/2000/svg" style="display:none;">
            <symbol id="svg-1075" viewBox="0 0 160 150">
                <path d="M124.3,80.3c20.5-1.1,32-18.4,34.8-31.5c4.7-22.6-6.7-55.4-81.5-47.7c-124.8,12.7-75.1,145.7-16.9,114
                            C99.9,93.7,86.4,82.3,124.3,80.3z"></path>
            </symbol>

        </svg>
        <svg xmlns="http://www.w3.org/2000/svg" style="display:none;">
            <symbol id="svg-1075" viewBox="0 0 160 150">
                <path d="M124.3,80.3c20.5-1.1,32-18.4,34.8-31.5c4.7-22.6-6.7-55.4-81.5-47.7c-124.8,12.7-75.1,145.7-16.9,114
                        C99.9,93.7,86.4,82.3,124.3,80.3z"></path>
            </symbol>

        </svg>
        <section class="st-6">


            <svg class="u-svg-link" preserveAspectRatio="none" viewBox="0 0 100 130" y="0px" x="0px">
                <use href="#svg-1074"></use>
            </svg>
            <div class="block-2">
                <h5 class="u-text u-text-default u-text-1"> EFFECTIVE EDUCATION <br>
                </h5>
                <h1 class="u-text u-text-2">The Institute for Effective Education </h1>
                <p class="u-text u-text-3">Image from <a href="https://www.freepik.com/photos/woman">Freepik</a>
                </p>

                <a href="#" class="link">Learn more</a>

            </div>

            <svg class="u-svg-link-3" preserveAspectRatio="none" viewBox="0 0 160 150" y="0px" x="0px">
                <use href="#svg-1075"></use>
            </svg>
            <div class="st-6-img"><img src="./public/images/-min.jpg" alt=""></div>


        </section>
        <svg xmlns="http://www.w3.org/2000/svg" style="display:none; ">
            <symbol id="svg-1077" viewBox="0 0 160 150">
                <path d="M157.4,45.5c11.3-39.1-16.3-50.2-43.8-43.8c-25.2,5.8-35.5,17.2-61,16.5C21.7,17.4,0,39.8,0,71.3
            c0,49.1,58.2,47.8,76.2,68.5c38.8,44.7,92.8,8.2,79.3-40.3C148.1,73.2,155.9,50.6,157.4,45.5z"></path>
            </symbol>

        </svg>

 <svg xmlns="http://www.w3.org/2000/svg" style="display:none; ">
                <symbol id="svg-1078" viewBox="0 8 160 150">
                    <path d="M138.9,102.2c-9.5,10.1-24.4,20.2-41.2,27.4C63.2,144.5,21,147.1,3.1,112.4c-9.9-19.1,6.5-28.8,11.8-45.7
			c5.3-16.9-11.4-32.3-5.1-49.9c1.8-4.9,4.9-9,8.9-11.9C24,1,30.8-0.8,37.8,0.3C43.6,1.2,49,3.5,54.3,5.7c8.8,3.7,17.4,7.1,26.3,9.8
			c15.7,4.7,31.3,3.7,47.1,7.2c8.5,1.9,16.7,5.6,22.6,11.8C170.3,55.7,155.8,84.1,138.9,102.2z"></path>
                </symbol>
    
            </svg>
        <section class="st-7">
            <svg class="u-svg-link-4" preserveAspectRatio="none" viewBox="0 0 130 110    0" y="0px" x="0px">
                <use href="#svg-1077"></use>
            </svg>
            <div class="div-st-7">
                <h2>An Effective Education</h2>
            </div>
            <div class="u-repeater-1">
                <div class="u-container-layout" >
                    <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                        fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
                        deserunt mollit anim id est laborum.</p>
                </div>
                <div class="u-container-layout" >
                    <p>Article evident arrived express highest men did boy. Mistress sensible entirely am so. Quick can
                        manor smart money hopes worth too. Comfort produce husband boy her had hearing. Law others
                        theirs passed but wishes. You day real less till dear read. Considered use dispatched melancholy
                        sympathize discretion led. </p>
                </div>
            </div>
            
            
        </section>
            <svg class="u-svg-link-5" preserveAspectRatio="none" viewBox="0 0 1 50 140    0" y="0px" x="0px">
                <use href="#svg-1078"></use>
            </svg>


            <svg xmlns="http://www.w3.org/2000/svg" style="display:none; ">
                <symbol id="svg-1079" viewBox="0 8 160 150">
                    <path d= "M 43.2 126.9 c 14.2 1.3 27.6 7 39.1 15.6 c 8.3 6.1 19.4 10.3 32.7 5.3 c 11.7 -4.4 18.6 -17.4 21 -30.2 c 2.6 -13.3 8.1 -25.9 15.7 -37.1 c 8.3 -12.1 10.8 -27.9 5.3 -42.7 C 150.5 20.3 134.6 9 117 7.6 C 107.9 6.9 98.8 5 90.1 1.9 C 83 -0.6 75 -0.7 67.4 2.1 c -9.9 3.7 -17 11.6 -20.1 21 c -3.3 10.1 -10.9 18 -20.6 22.2 c -0.1 0 -0.1 0.1 -0.2 0.1 c -20.3 8.9 -31 32 -24.6 53.2 C 6.9 115.6 25.2 125.2 43.2 126.9 Z"></path>  
                </symbol>
    
            </svg>

            <section class="st-8">
                <svg class="u-svg-link-6" preserveAspectRatio="none" viewBox="0 0 160 140    0" y="0px" x="0px">
                    <use href="#svg-1079"></use>
                </svg>
                <div class="st-8-img">
                    <img src="./public/images/hjjhhj.jpg" alt="">
                </div>
                <div class="block-3">
                    <h5 class="u-text u-text-default u-text-1"> QUALITY EDUCATION <br>
                    </h5>
                    <h1 class="u-text u-text-2">Education for health and well-being</h1>
                    <p class="u-text u-text-3">Image from <a href="https://www.freepik.com/photos/woman">Freepik</a>
                    </p>
    
                    <a href="#" class="link">Learn more</a>
    
                </div>
            </section>
           </div>


</body>

</html>