<h1>Projet Université</h1>
<section>
    <article>
        <h2>Premier article</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non minima facilis rem totam qui. Voluptate
            optio qui accusamus possimus dolorum odit,
            dolor error porro facilis suscipit eligendi iste cupiditate voluptatibus! Lorem ipsum dolor sit amet
            consectetur adipisicing elit. Quaerat laboriosam nam consequuntur alias odio, sequi quae molestias
            obcaecati. Vitae corrupti recusandae quisquam esse alias explicabo expedita officia, sapiente
            maiores autem?</p>
    </article>
    <article>
        <h2>Deuxième article</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non minima facilis rem totam qui. Voluptate
            optio qui accusamus possimus dolorum odit,
            dolor error porro facilis suscipit eligendi iste cupiditate voluptatibus! Lorem ipsum dolor, sit
            amet consectetur adipisicing elit. Saepe quae quam voluptatibus corporis asperiores eius, quos iste
            recusandae eos doloribus expedita odit laboriosam, soluta sit praesentium a voluptate, qui illum?
        </p>
    </article>
</section>
<aside>
    <h3>Infos complémentaires</h3>
    <ul>
        <li>Evénement 1</li>
        <li>Evénement 2</li>
        <li>Evénement 3</li>
        <li>Evénement 4</li>
    </ul>
</aside>