<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="slick-1.8.1/slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="slick-1.8.1/slick/slick-theme.css" /> -->
    <link rel="stylesheet" href="../public/css/normalize.css" />
    <link rel="stylesheet" href="../public/css/style.css" />
    <script src="../public/js/test.js"></script>
    <title>Exemple - ProjetMVC</title>
</head>

<!-- BODY -->

<body>
    <!-- HEADER COMMUN-->
    <header>
        <nav class="menu">
            <a href="index.php?url=home">Accueil</a>
            <a href="index.php?url=enregistrer">Absence/Retard</a>
            <a href="index.php?url=note">Note</a>
            <a href="#">Devoir/Contrôle</a>
            <a href="index.php?url=logout" class="item">Se déconnecter</a>
        </nav>
        <div class="right-menu">
            <?php if (isset($_SESSION['firstname'])): ?>
            <a href="index.php?url=profile&id=<?php echo $_SESSION['user_id']; ?>" class="item">Mon profil</a>
            <a href="index.php?url=logout" class="item">Se déconnecter</a>
            <?php  else: ?>
                <button class='btn' onclick="connexion()"> Connecter</button>
                <div class="connexion">
                    <ul >
                        <li><a href="index.php?url=loginEnseignant" class="item">Enseignant</a></li>
                        <li><a href="index.php?url=loginEtudiant" class="item">Etudiant</a></li>
                    </ul> 
               </div>
            <?php endif ?>
        </div>
    </header>

    <!-- MAIN -->
    <main>
        <!-- AFFICHAGE DU TEMPLATE CORRESPONDANT À LA VIEW VISÉ -->
        <?php include $this->template.'.phtml'?>
    </main>

    <!-- FOOTER COMMUN-->
    <footer>
        <small>(c) Copyright 2020 - Tous droits réservés <br>Fait pour exemple</small>
    </footer>
    <!-- IMPORTATION JS/SLICK -->
    <script type="text/javascript" src="slick-1.8.1/slick/slick.min.js"></script>
    <script src="js/main.js"></script>
</body>

</html>