
    <?php if (!empty($this->error)) : ?>
    <div class="error"><?= $this->error ?></div>
<?php endif; ?>
    <svg xmlns="http://www.w3.org/2000/svg" style="display:none; ">
                <symbol id="svg-1080" viewBox="0 5 160 150">
                                <path d="M10.3,39.9c-18.2,24.9-9.2,62.5,4,87.4c8.2,15.4,23,36.1,48.6,32.2c5.8-0.9,11.1-3.2,16.9-4.3c17.8-3.4,37.9,4.7,54.5-1.5
                        c6.6-2.5,11.6-6.9,15.5-11.8c12.2-15.3,13.7-35.6,3.8-51.9c-6.9-11.5-19-20.9-23.6-33.1c-4.5-11.9-1.4-24.9-4.7-37.1
                        C121.1,5,103.7-5.6,85.7,3.1c-6.8,3.3-12.6,7.7-20,10.2C58,15.9,49.5,16.6,41.6,19C26.8,23.6,16.7,31,10.3,39.9z"></path>
                    
                </symbol>
    
            </svg>
    <section class="st-9">

<div class="st-9-h1"><h1>Espace de connexion</h1></div>
<svg class="u-svg-link-7" preserveAspectRatio="none" viewBox="0 0 160 160 " y="0px" x="0px">
    <use href="#svg-1080"></use>
</svg>

<div class="st-9-img">
    <img src="./public/images/qewee.jpg" alt="">
</div>

<div class="block-st-9">
<form action="<?=$_SERVER['REQUEST_URI']?>" method="POST" >
        <div class="u-form-group  u-form-name">
            <label for="email" class="l-email" >Email</label>
            <input type="text" placeholder="Entrer une address email" class="email" name="email">
        </div>
        <div class="u-form-group u-form-name">
            <label for="password" class="l-password">Mot de passe</label>
            <input type="password" placeholder="Entrer un mot de passe  " class="password" name="password">
        </div>
        <input type="submit" value="Se connecter" class="submit">
</form>
</div>
<div class="circle-st-9">


</div>
</section>