<!-- <section id="login" class="col s12">
    <form class="col s12" action="<?=$_SERVER['REQUEST_URI']?>" method="POST">
        <article class="form-login">
            <h1 class="hello">Connectez-vous</h1>

            <div class="input-field col s12">
                <label for="email">Email</label>
                <input id="email" name="email" type="email" class="validate">
            </div>

            <div class="input-field col s12">
                <label for="password">Mot de passe</label>
                <input id="password" name="password" type="password" class="validate">
            </div>

            <div class="checkbox-container">
                <input type="checkbox" required>
                <div class="text-checkbox">I agree with the terms of service.</div>
            </div>

            <div>
                <button class="btn-login" type="submit" name="submit" >Se connecter</button>
                <a href="">Mot de passe oublié?</a>
            </div>
        </article>
    </form>
</section> -->

<section class="u-align-center-sm u-align-center-xs u-clearfix u-section-8" id="sec-0600">
        <div class="u-clearfix u-sheet u-sheet-1">
            <h1 class="u-align-center u-text u-text-palette-3-base u-text-1">Espace de connexion</h1>
            <div class="u-rotation-parent u-rotation-parent-1">
                <div class="u-flip-horizontal u-shape u-shape-svg u-text-palette-3-base u-shape-1">
                    <svg class="u-svg-link" preserveAspectRatio="none" viewBox="0 0 160 160" style="">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-b1ce"></use>
                    </svg>
                    <svg class="u-svg-content" viewBox="0 0 160 160" x="0px" y="0px" id="svg-b1ce"
                        style="enable-background:new 0 0 160 160;">
                        <path d="M10.3,39.9c-18.2,24.9-9.2,62.5,4,87.4c8.2,15.4,23,36.1,48.6,32.2c5.8-0.9,11.1-3.2,16.9-4.3c17.8-3.4,37.9,4.7,54.5-1.5
	c6.6-2.5,11.6-6.9,15.5-11.8c12.2-15.3,13.7-35.6,3.8-51.9c-6.9-11.5-19-20.9-23.6-33.1c-4.5-11.9-1.4-24.9-4.7-37.1
	C121.1,5,103.7-5.6,85.7,3.1c-6.8,3.3-12.6,7.7-20,10.2C58,15.9,49.5,16.6,41.6,19C26.8,23.6,16.7,31,10.3,39.9z"></path>
                    </svg>
                </div>
            </div>
            <div class="u-align-left u-image u-image-circle u-image-1" data-image-width="800" data-image-height="786">
            </div>
            <div class="u-gradient u-shape u-shape-circle u-shape-2"></div>
            <div class="u-expanded-width-xs u-form u-radius-10 u-white u-form-1">
                <form action="<?=$_SERVER['REQUEST_URI']?>"
                    class="u-clearfix u-form-spacing-15 u-form-vertical u-inner-form" source="email" name="form"
                    style="padding: 28px;" method="POST">
                    <div class="u-form-group u-form-name">
                        <label for="name-4c18" class="u-label">Email</label>
                        <input type="text" placeholder="Entrer un addresse email" id="name-4c18" name="text-1"
                            class="u-border-2 u-border-grey-5 u-grey-5 u-input u-input-rectangle u-radius-10"
                            required="">
                    </div>
                    <div class="u-form-email u-form-group">
                        <label for="email-4c18" class="u-label">Mot de passe</label>
                        <input type="email" placeholder="Entrer  un mot de passe " id="email-4c18" name="text"
                            class="u-border-2 u-border-grey-5 u-grey-5 u-input u-input-rectangle u-radius-10"
                            required="">
                    </div>
                    <div class="checkbox-container">
                <input type="checkbox" required>
                <div class="text-checkbox">I agree with the terms of service.</div>
            </div>

                    <div class="u-align-right u-form-group u-form-submit">
                        <a href="#"
                            class="u-active-palette-3-base u-border-5 u-border-active-palette-3-base u-border-hover-palette-3-base u-border-palette-1-base u-btn u-btn-round u-btn-submit u-button-style u-hover-palette-3-base u-palette-1-base u-radius-50 u-btn-1">Submit</a>
                        <input type="submit" value="submit" class="u-form-control-hidden">
                    </div>
                    <div class="u-form-send-message u-form-send-success"> Thank you! Your message has been sent. </div>
                    <div class="u-form-send-error u-form-send-message"> Unable to send your message. Please fix errors
                        then try again. </div>
                    <input type="hidden" value="" name="recaptchaResponse">
                    <input type="hidden" name="formServices" value="88d1f2dc-b0e0-8b4a-bfa1-3381fd1c0112">
                </form>
            </div>
        </div>
    </section>