<!DOCTYPE html>
<html lang="fr">
<head>
    <!-- <meta charset="UTF-8">
    <title>Liste des présences</title>
    <style>
        table {
            width: 90%;
            margin: auto;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ccc;
            padding: 10px;
            text-align: center;
        }
        th {
            background: #f0f0f0;
        }
        .alerte {
            color: red;
            font-weight: bold;
        }
    </style> -->
</head>
<body>
<h2 style="text-align: center;">Tableau de suivi des présences</h2>

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Email</th>
            <th>Absences</th>
            <th>Retards</th>
            <th>Vérification</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($etudiants as $etudiant): ?>
            <tr>
                <td><?= $etudiant['id']?></td>
                <td><?= htmlspecialchars($etudiant['nom']) ?></td>
                <td><?= htmlspecialchars($etudiant['prenom']) ?></td>
                <td><?= htmlspecialchars($etudiant['email']) ?></td>
                <td><?= $etudiant['total_absences'] ?? 0 ?></td>
                <td><?= $etudiant['total_retards'] ?? 0 ?></td>
                <td>
                   <button class='alerte'><a href='verif-absence'>Vérifier</a></button>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</body>
</html>